### PR TITLE
[AJ-1296] Rename data to workspace-data

### PR DESCRIPTION
**Pull request by nawatts**
Still working on organizing UI code for the Data tab...

This moves src/data to src/workspace-data and updates import paths accordingly.

Apologies for the churn here. I originally named the folder "data" after the "Data" tab, but got feedback that that name was too generic given how many other "data" related things there are in Terra.

### CODE REVIEW

**Review by s-rubenstein — APPROVED** [review]
Looks fine - happy with this rename!

**Comment by nawatts** [comment]
Rebased to resolve merge conflict.

**Review by THWiseman — APPROVED** [review]

**Review by jladieu — APPROVED** [review]
Just curious, did you get any help from the IDE doing this, or was this a tedious find/replace?  I know how I'd do this with IntelliJ/Java but wondering how you can accomplish the same in TS/VSCode.

**Comment by nawatts** [comment]
A tedious find/replace.

Though now that you mention, VS Code can update imports if you move files from within VS Code. That's probably what I should have done.
https://code.visualstudio.com/docs/typescript/typescript-refactoring#_update-imports-on-file-move

**Review by kpierre13 — APPROVED** [review]

**Pull request merged**
