### PR TITLE
ID-1207 Tell DRSHub a Request comes from Terra UI

### PR DESCRIPTION
**Pull request by tlangs**
### What
- Tell DRSHub that a request is coming from Terra UI

### Why
- Inquiring minds want to know!

### Testing strategy

- [ ]

### CODE REVIEW

**Comment by nawatts** [comment]
Related to this, Terra UI already sends an `X-App-Id: Saturn` in requests to several services.

https://github.com/DataBiosphere/terra-ui/blob/b0b14fc9ecc6b0e7d31a00bf1cf30f0d3c865fc5/src/libs/ajax/ajax-common.ts#L128-L132

https://github.com/DataBiosphere/terra-ui/blob/b0b14fc9ecc6b0e7d31a00bf1cf30f0d3c865fc5/src/libs/ajax/ajax-common.ts#L208-L273

**Comment by tlangs** [comment]
@nawatts Do you know if this is a common pattern? I think it might be a bit more elegant to do this with a header rather than a body param

**Comment by nawatts** [comment]
I'd say it's a common pattern. Terra UI is already sending it in requests to several services, though I don't know which of those services actually look at the header.

But generally, I'd view this as similar to the `User-Agent` header.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by tlangs** [comment]
Thanks for the info! I'll change my approach!

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Pull request closed without merging**
