### PR TITLE
fix notification font [SATURN-882]

### PR DESCRIPTION
**Pull request by panentheos**
Make sure our overrides come last in the load order.

### CODE REVIEW

**Comment by katevoss** [comment]
@panentheos How should we go about testing this? It looks fine, but I don't notice a difference in the fonts for the notification message.

**Comment by panentheos** [comment]
@katevoss There should be a visible change, you might to do a full refresh if you're switching branches. The intended behavior is for the notifications to use Montserrat, instead of Arial.

**Comment by petesantos** [comment]
When I view this on my local machine the change works as expected. I can see the difference between the fonts and confirmed the ordering of the CSS in the source. However, when I go to bvdp-saturn-dev.appspot.com or app.terra.bio I am seeing the Montserrat font right now.

The CSS is minified and loaded in chunks on these two sites, but this does not seem to be the case in the local dev environment. I looked at the CSS source in bvdp-saturn-dev and found that the easymde css (added to chunk 2) is loaded before the react-notifications CSS (added to chunk 3).

My only concern is that this change, when fully built could have the reverse of the intended effect.

**Comment by panentheos** [comment]
It does look like the CSS is bundled differently in local vs prod, so this issue likely only affects local builds. The PR site uses the same build process as prod, so you can check that everything looks good there.

**Review by petesantos — APPROVED** [review]
Checked on PR site, looks good

**Pull request merged**
