### PR TITLE
[CA-1291] Add KidsFirst provider

### PR DESCRIPTION
**Pull request by marctalbott**
Ticket: [CA-1291](https://broadworkbench.atlassian.net/browse/CA-1291)
Add KidsFirst to the list of providers so that it will show up on the right side of the profile page

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Comment by marctalbott** [comment]
Merge blocked by release of https://github.com/DataBiosphere/bond/pull/170

**Review by andy7i — APPROVED** [review]
My mind is blown that all this requires is a one liner (in addition to the config changes). Might be worth verifying the change manually after the config changes are in?

**Comment by marctalbott** [comment]
> My mind is blown that all this requires is a one liner (in addition to the config changes). Might be worth verifying the change manually after the config changes are in?

Me too! Good call -- I'll definitely double check it before I merge. I was very pleased with how simple this was and the UI I spun up seemed like it would work once the config changes are in, so fingers crossed!

**Review by gpolumbo-broad — APPROVED** [review]

**Comment by gpolumbo-broad** [comment]
> My mind is blown that all this requires is a one liner (in addition to the config changes). Might be worth verifying the change manually after the config changes are in?

Sometimes we get things right!  We knew that adding new providers was going to be a thing that needed to happen, so we built it to support that.  https://www.youtube.com/watch?v=edCqF_NtpOQ

**Review by zarsky-broad — APPROVED** [review]
Just thumbing this so it can be merged when the time comes.

**Comment by kyuksel** [comment]
> Merge blocked by release of DataBiosphere/bond#170

@marctalbott It looks like the Bond PR was merged. Is this good to merge now?

**Comment by breilly2** [comment]
Last I knew, this is still waiting an a Memorandum of Understanding before releasing to production.

**Comment by marctalbott** [comment]
As Brian said, we are still waiting on the MoU before releasing this. When that is ready, we'll also need to get the production KidsFirst oauth client id and secret before we'll be able to link accounts through Bond

**Comment by kyuksel** [comment]
@marctalbott @breilly2 Any updates on this PR?

**Comment by marctalbott** [comment]
@kyuksel We will be merging this PR either this sprint or next sprint. I believe we just received the MoU

**Pull request merged**
