### PR TITLE
Update AMP PD logo in datasets page

### PR DESCRIPTION
**Pull request by wnojopra**
The AMP PD Outreach Working Group has requested that the logo on the datasets page be updated to match https://amp-pd.org/ . Tested by running locally:
Screenshot 2021-02-24 9 34 13 AM

### CODE REVIEW

**Comment by wnojopra** [comment]
Hi @DataBiosphere/terra-devs , is there anything for me to do here? The circleci tests are failing because I don't have the necessary permissions.

**Review by mbookman — APPROVED** [review]
LGTM

**Review by zarsky-broad — APPROVED** [review]
Looks fine to me. We're working on finding a second person to review.

**Review by breilly2 — APPROVED** [review]
👍   Looks good to me. I didn't test, but everything appears to be in place and you included a screenshot.

TOL: Deleting the old image right away means that, for anyone who has Terra open in their browser and doesn't reload after this is deployed, I think they will see a broken image.

**Comment by wnojopra** [comment]
Thanks! I decided to put back the old image for the reason breilly2 mentioned. @breilly2  @zarsky-broad could one of you merge for me? I cannot merge because I don't have write access.

**Comment by zarsky-broad** [comment]
The easiest option might be to make the new image have the same name as the old image?

**Comment by wnojopra** [comment]
Thanks, that sounds reasonable to me. Done.

**Pull request merged**
