### PR TITLE
[CA-1288] Revert "Sr v1 workspace integration tests (#2500)"

### PR DESCRIPTION
**Pull request by s-rubenstein**
This reverts commit 6dde7ba8d1866921efa658905e2709baeccdf297.

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Comment by s-rubenstein** [comment]
This PR was generated by running `git revert 6dde7ba8d1866921efa658905e2709baeccdf297` on a clean branch from dev

**Review by MatthewBemis — APPROVED** [review]
The revert looks legit to me 👍

**Review by zarsky-broad — APPROVED** [review]
Do you want to just disable the lines that activate them but leave the code in, instead of fully deleting them?

**Review by marctalbott — APPROVED** [review]

**Comment by s-rubenstein** [comment]
Tests are failing with this same error if I check out code 5 commits back. I am going to merge this.

**Pull request merged**
