### PR TITLE
[WX-1739] Create WorkflowWrapper

### PR DESCRIPTION
**Pull request by kpierre13**
### What
- Creating a workflow wrapper and splitting tabs into their own components

### Why
- Firecloud UI Migration
### Testing strategy

- [x] Unit tests

[WX-1739]: https://broadworkbench.atlassian.net/browse/WX-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by aednichols — COMMENTED** [review]
I recognize that our discussion of method configs was potentially ill-timed with respect to this PR...

I am concerned that the code has functionality to display published method configs, when we turned off the ability to publish new configs a few years ago [0].

This means that most users will see zero configs with no ability to create more.

[0] Publishing a config was only possible when viewing a workspace in the old FireCloud UI; that part of the UI is disabled.

**Comment by kpierre13** [comment]
@aednichols You're right that this change will show published method configs but not have anyway to create new ones, but since we don't have a clear answer from product about what to do with this feature, I opted for leaving it as part of the PR. It's a lot easier to remove a component than trying to reimplement it in the future. Also, since this isn't user facing yet, I think it should be alright to stick around for a little while longer. What do you think?

**Comment by aednichols** [comment]
I definitely see where you're coming from with the feature not being turned on yet, and no discussion yet with product.

I do somewhat disagree on it being easier to remove a component in the future. Shipping something we maybe intend to remove can create confusion on the dev team, as we have to re-explain that "that's in there now, but don't worry about it because it's going away".

As a middle ground, would you be OK with checking in that code behind an `if (false)` with a comment that says something like "published method configs are on ice for now"?

**Comment by kpierre13** [comment]
@aednichols Made the change as we discussed during mob time in the followup PR: https://github.com/DataBiosphere/terra-ui/pull/4999

**Review by aednichols — APPROVED** [review]

**Comment by salonishah11** [comment]
@kpierre13 When testing the changes I noticed that when I change snapshot version, changes are not reflected in the UI. Also, changing the snapshot version doesn't seem to be working and I see this error in console. In this screenshot I was trying to switch snapshot version from 12 to 5.

Screenshot 2024-08-13 at 4 21 29 PM

**Review by salonishah11 — APPROVED** [review]

**Pull request merged**
