### PR TITLE
Dedupe groups

### LINKED ISSUE #867: Groups page shows same group twice
baseline-researchers is shown twice. I am an Admin of baseline-researchers.

groups

### PR DESCRIPTION
**Pull request by MattPutnam**
Fixes #867 

Remove 'member' entries that are already present as admin

Also make sort non case-sensitive

### CODE REVIEW

**Review by panentheos — COMMENTED** [review]
Based on a discussion this morning, we need to think more about what we're going to do here. Currently this hides some potentially important information about the state of the data, which is potentially problematic.

**Comment by MattPutnam** [comment]
Could we merge them together instead? If one appears in both, show it as "Admin/Member" or something like that?

**Comment by breilly2** [comment]
Yes, that and change editing to use checkboxes instead of radio buttons. @MattPutnam I can work on this if you're busy with 870/920.

**Comment by panentheos** [comment]
Closing this since we're going to use a different approach.

**Pull request closed without merging**
