### PR TITLE
log test info without useless stack trace [POL-155]

### PR DESCRIPTION
**Pull request by zarsky-broad**
cleans up test logging.

before:
Screen Shot 2022-01-11 at 14 03 25

after:
Screen Shot 2022-01-11 at 14 03 35

### CODE REVIEW

**Comment by cahrens** [comment]
@zarsky-broad what is the problem you are trying to solve here? Can you also link a ticket that explains the problem?

When I've been running the integration tests, I do see the console.info statements.

**Comment by zarsky-broad** [comment]
yup, sorry @cahrens, you beat me to it

**Comment by cahrens** [comment]
> yup, sorry @cahrens, you beat me to it

Nice! I had accepted the extra cruft as "just the way things are", but it's definitely much cleaner with this.

**Comment by cahrens** [comment]
Change or remove `logPageConsoleMessages`?

**Comment by zarsky-broad** [comment]
I left the stack trace on that one, since it's called mid-run it might have useful stack trace. (I don't know)

**Review by cahrens — APPROVED** [review]

**Review by kyuksel — APPROVED** [review]

**Pull request merged**
