### PR TITLE
[Bug Fix] Updated checkbox to labeled checkbox, cause i didnt know it existed

### PR DESCRIPTION
**Pull request by lu-c**
Simple small change

### CODE REVIEW

**Review by petesantos — APPROVED** [review]

**Comment by kyuksel** [comment]
@lu-c FYI that it looks like the CI build failed due to a linting error:

image

**Comment by lu-c** [comment]
> @lu-c FYI that it looks like the CI build failed due to a linting error:
> 
> image

Oh! Thank you, sorry!

**Review by kyuksel — APPROVED** [review]

**Comment by kyuksel** [comment]
> Oh! Thank you, sorry!

@lu-c No problem. The PR is good to merge with all checks passed 😊

**Comment by kyuksel** [comment]
@lu-c would you like to merge this PR before it requires more rebasing?

**Pull request merged**
