### PR TITLE
[CORE-184] Add Public Roadmap Banner to Home Page

### PR DESCRIPTION
**Pull request by kevinmarete**
### What

This PR introduces a new banner to the home page(s) of all `terra.bio` home page(s), promoting the Terra public roadmap. 

- Added a banner to the all `terra.bio` home page(s) with the text: “_Stay connected: see what's new, what's next, and try out the latest features on Terra._” The banner includes a [link](https://support.terra.bio/hc/en-us/sections/30968105851931-Terra-Roadmap.) to the Terra public roadmap:
- Added the [Terra Roadmap link](https://support.terra.bio/hc/en-us/sections/30968105851931-Terra-Roadmap) to the "Platform News" section in the left-hand navigation.

### Why
- The banner encourages users to stay updated with Terra's latest features and upcoming plans.

### Testing strategy

- Manual Testing
  - Verified the banner appears on the `app.terra.bio` home page as designed.
  - Confirm the link redirects to the Terra Roadmap.
  - Ensure the "Platform News" section in the left-hand navigation includes the roadmap link.

**Landing Page**

Landing Page

**Platform News Sidebar**

Platform News

### CODE REVIEW

**Comment by admull** [comment]
The banner should not repeat like that. Either the height is too big or we need a different image. I'm out next week, so work with Lou directly if you need to.

**Comment by kevinmarete** [comment]
> The banner should not repeat like that. Either the height is too big or we need a different image. I'm out next week, so work with Lou directly if you need to.

This has been fixed: https://github.com/DataBiosphere/terra-ui/pull/5178/commits/2e709e0bf795b14e4fa988f6183b58d9187e2470

no-repeat-image

**Review by calypsomatic — APPROVED** [review]
Looks great but I'm not authorized to see the page it links to

**Review by dvoet — APPROVED** [review]

**Comment by kevinmarete** [comment]
> Looks great but I'm not authorized to see the page it links to

This will be publicly accessible tomorrow!

**Review by kilonzi — APPROVED** [review]
banner looks great across all branded sites

**Pull request merged**
