### PR TITLE
[IA-4380] add lodash and hyperscript type declarations

### PR DESCRIPTION
**Pull request by ghost**
## Summary of changes:
Added the public DTO files for lodash/fp and hyperscript as we had not yet added them. We already had the DTOs for lodash, but a newer version was released that also typed FP so now we can flawlessly convert our lodash/hs code to typescript without pesky typeErrors.

### What
- upgraded lodash types
- added hyperscript types

### Why
- to increase ease/stability of typescript conversions

### Testing strategy
- [x] ts linter still passes all files

### CODE REVIEW

**Comment by nawatts** [comment]
I don't think we need `@types/hyperscript'. We don't directly use `hyperscript` and have our own type definitions for `react-hyperscript-helpers`.

**Comment by ghost** [comment]
> I don't think we need `@types/hyperscript'. We don't directly use `hyperscript`and have our own type definitions for`react-hyperscript-helpers`.

I didn't realize until it was too late on that front, I was creating this PR as an audit of trying to move away from depending on our own types. We should consider releasing our types for react-hyperscript-helpers via definitelyTyped and installing it thru our package.json

**Comment by nawatts** [comment]
Our type definitions for `react-hyperscript-helpers` are not complete. They only cover the parts we use and the way we use them.

**Comment by ghost** [comment]
> Our type definitions for `react-hyperscript-helpers` are not complete. They only cover the parts we use and the way we use them.

alright, thanks. perhaps this means at some point we should switch away from react-hyperscript-helpers, it hasn't been touched in 6 years and isn't very conventional

**Pull request closed without merging**
