### PR TITLE
[IA-3225] Beta release analysis tab

### PR DESCRIPTION
**Pull request by jdcanas**
Puts in links and reveals toggle in notebooks tab.

Note that the `learn more` link blog post is not posted yet, so it will bring you to terra.bio until it is created.  

The intended release date is 4/20

### CODE REVIEW

**Comment by Qi77Qi** [comment]
shall we enable toggle in this same PR?

**Comment by jdcanas** [comment]
This also reveals the toggle. It's the [line](https://github.com/DataBiosphere/terra-ui/pull/2958/files#diff-425a6632e5b0cfa401a1b984006a440fd375cea2976caca7587d1c0954237542L439) where `display: 'none'` is changed to `display: 'flex'`

image

**Review by dmohs — APPROVED** [review]
I wish I'd seen this earlier. Any PR that removes more code than it adds is practically and automatic approval as far as I'm concerned. I love that this one is clearly tying up loose ends.

**Review by Qi77Qi — APPROVED** [review]
PR site looks good to me other than the blog post doesn't exist yet..but the plan is to have that published early next week

**Comment by Qi77Qi** [comment]
reminder to update https://github.com/DataBiosphere/terra-ui/blob/dev/src/pages/workspaces/workspace/applications/AppLauncher.js#L53

**Pull request merged**
