### PR TITLE
Deploy PRs via Circle

### PR DESCRIPTION
**Pull request by dmohs**

### CODE REVIEW

**Review by zarsky-broad — APPROVED** [review]
Should the job be called deploy branch rather than deploy PR? This will run against any pushed branch, right?

**Comment by bradtaylor** [comment]
@dmohs I linked this PR with the issue, since PRs show up on the board. Can we commit to doing this in the future? Otherwise the board is confusing for me. It's actually a really nice feature of the board to see the relevant PRs for an issue, if we use it. Sorry if it's annoying, but it would be a help to me.

**Comment by dmohs** [comment]
@zarsky-broad I couldn't figure out how to get it to only run on PRs, so there is a conditional there to deploy only if `CIRCLE_PULL_REQUEST` is defined. I can see the benefit of building all branches, but this scheme only works reliably using the PR index, so I'm not sure how I'd modify it to support that case.

**Comment by dmohs** [comment]
@bradtaylor Happy to do this if you come to my desk and show me how. I couldn't find the option in ZenHub's UI.

**Pull request merged**
