### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by zarsky-broad**
Tested (fairly?) thoroughly.

### CODE REVIEW

**Review by katevoss — COMMENTED** [review]
I tried to run it locally and got this error:
```
Module not found: Can't resolve 'easymde/dist/easymde.min.css' in '/Users/kvoss/Documents/git/saturn-ui/src/pages/workspaces/workspace'
```

**Comment by zarsky-broad** [comment]
@katevoss did you npm install first?

**Comment by breilly2** [comment]
I started looking through this from an API standpoint, particularly where the major version changed. I got through `filesize` and `path-to-regexp` yesterday before being pulled away. Those looked okay, mostly because we make such little use of them and how we do use them is very straightforward. The remaining major version bump is `react-simplemde-editor` and I'm also interested in the changes to `react-select` because, unlike some other libraries, we use quite a few customization options and behavior changes could be very subtle.

@zarsky-broad, did you come across anything significant from this angle that would be helpful to know about when reviewing?

**Comment by katevoss** [comment]
Works now! I tested loading and interacting with workspaces, notebooks, etc. Looks good to me.
One day I'll remember to `npm install` first.

**Comment by zarsky-broad** [comment]
Checked all the change notes, none of the larger version bumps affect us (the css import change is due to the change in react-simplemde)

**Pull request merged**
