### PR TITLE
[IA-3271] fix memory leak in igv viewer

### PR DESCRIPTION
**Pull request by jordansafer**
Fixed a memory leak coming in and out of the IGV viewer page.

### Before (3 visits to IGV viewer create 3 allocation for IGV lib, about 10 MB each time)
Screen Shot 2022-03-24 at 4 50 37 PM

### After (3 visits to the IGV viewer, no allocations left after the viewer is exited each time)
Screen Shot 2022-03-24 at 4 51 01 PM

### CODE REVIEW

**Comment by zarsky-broad** [comment]
Instead of calling it from the onClick, you can return a cleanup function in the onMount that'll be run at unmount time.
(incidentally, I think you want to use a ref instead of state to avoid an extra render)

**Review by davidangb — APPROVED** [review]
nice find on this!

**Comment by jordansafer** [comment]
> Instead of calling it from the onClick, you can return a cleanup function in the onMount that'll be run at unmount time. (incidentally, I think you want to use a ref instead of state to avoid an extra render)

Thanks! Addressed, latest memory profile test post-fix:
Screen Shot 2022-03-24 at 7 16 41 PM

(looks like there may be a much smaller ~100kb leak on the workspace data page, but I haven't investigated deeply to see if this clears out)

**Review by kyuksel — COMMENTED** [review]
LGTM but I'll let @zarsky-broad re-review and 👍🏼 
Thanks for taking care of this!

**Review by zarsky-broad — APPROVED** [review]
Code looks good.

**Pull request merged**
