### PR TITLE
DSPDC-181 Add NeMO archive to featured datasets.

### PR DESCRIPTION
**Pull request by danxmoran**
The link takes you to the NeMO homepage, which shows some summary info:
Screen Shot 2019-03-19 at 12 56 44 PM

From there, users can search for relevant info:
Screen Shot 2019-03-19 at 12 57 05 PM

They can then add files to their "Download Cart", and select to export to Terra instead of generating a download manifest:
Screen Shot 2019-03-19 at 12 57 26 PM

### CODE REVIEW

**Review by zarsky-broad — COMMENTED** [review]
Ran the svg through https://jakearchibald.github.io/svgomg/ and cut the file size by half, check it out.

Turn on everything but "xmlns" and "remove style elements", precision of 1 seems sufficient.

**Comment by danxmoran** [comment]
@zarsky-broad done! Thanks for the suggestion.

**Review by zarsky-broad — APPROVED** [review]
FYI, the export to terra button there doesn't appear to do anything at the moment.

**Comment by danxmoran** [comment]
@zarsky-broad do you see any errors in your console / network tab when you click the button? It's working for me in both FF and Chrome (there's a slight delay between click and redirect, but it gets there eventually)

**Comment by zarsky-broad** [comment]
My steps: from [here](http://portal.nemoarchive.org/search/s?facetTab=cases&filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.study_name%22,%22value%22:%5B%22U19%20Huang%22%5D%7D%7D,%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.sample_organism%22,%22value%22:%5B%22Mouse%22%5D%7D%7D%5D%7D) click add all files to cart, then click export to Terra. I see a 500 in the console.

**Comment by danxmoran** [comment]
Thanks! I'll report it back to NeMO.

**Pull request merged**
