### PR TITLE
[AJ-374] Add a hotfix job for circleCI to trigger integration tests via the hotfix tag for a commit

### PR DESCRIPTION
**Pull request by jordansafer**
<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Review by nawatts — CHANGES_REQUESTED** [review]
Since the `integration-tests-alpha/staging` jobs test whatever is on alpha/staging, it seems like this approach requires some manual coordination. If I'm understanding correctly, testing a hotfix here would require:
* Merging to the `dev` branch, which automatically triggers a deploy to alpha/staging.
* Watching the alpha/staging deploys and waiting for them to complete.
* Pushing a hotfix tag for the commit in the `dev` branch, which would run these tests.

Based on the conversation in Slack, it sounds like we're ok with the extra overhead of running tests on alpha/staging on every commit to `dev`. Thus, adding `integration-tests-alpha/staging` to the `build-deploy` workflow would cover the cases where we need to run those tests for a hotfix and remove the manual steps of waiting for the deploys to complete and pushing a tag.

**Comment by jordansafer** [comment]
> Since the `integration-tests-alpha/staging` jobs test whatever is on alpha/staging, it seems like this approach requires some manual coordination. If I'm understanding correctly, testing a hotfix here would require:
> 
>     * Merging to the `dev` branch, which automatically triggers a deploy to alpha/staging.
> 
>     * Watching the alpha/staging deploys and waiting for them to complete.
> 
>     * Pushing a hotfix tag for the commit in the `dev` branch, which would run these tests.
> 
> 
> Based on the conversation in Slack, it sounds like we're ok with the extra overhead of running tests on alpha/staging on every commit to `dev`. Thus, adding `integration-tests-alpha/staging` to the `build-deploy` workflow would cover the cases where we need to run those tests for a hotfix and remove the manual steps of waiting for the deploys to complete and pushing a tag.

Updated- As currently configured, the tests should run after deploying the changes to alpha and staging respectively.

**Review by nawatts — APPROVED** [review]

**Review by xuscrbw — APPROVED** [review]
LGTM, tests are flaky. Wondering if there's something going on rn

**Comment by cahrens** [comment]
@xuscrbw I looked at the logs for one of the workspaces that failed to delete. It hit a 503-- message:35.191.1.227 - 114925642006220098835 "scarlett.flowerpicker@test.firecloud.org" "Saturn" [2022-04-06T12:37:52.956-0400] 635 - "DELETE /api/workspaces/saturn-integration-test-dev/terra-ui-test-workspace-faa67e74-3674-43e3-aee7-e20368eccdbb HTTP/1.1" 503 647 "http://localhost:3000/" "http://localhost:3000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4889.0 Safari/537.36". This isn't something I've seen before, so I think it is worth investigation.

**Comment by xuscrbw** [comment]
Yep, looking into it now.

I think there was an issue with workspace clean up at the end of the tests.

**Pull request merged**
