### PR TITLE
[AN-156] Broad Methods Repository: "workflows" to "methods"

### PR DESCRIPTION
**Pull request by sam-schu**
### What was done:
- Updated user-facing instances of the word "workflow" in the Broad Methods Repository referring to methods inside the repo to use the word "method" instead.
- Changed the methods repo base URL from `/#workflows` to `/#methods`.
- Updated the title of the Methods Repo section of the site as visible in the top bar and the main methods list page's browser tab title to "Broad Methods Repository."
- Updated certain internal wording (e.g., comments, test names, etc.) that refer specifically to UI elements now using the word "method" to use "method" instead of "workflow."
- Removed the unused `title` field, previously given the value "Workflows," from `WrapWorkflowOptions`.
- Improved typing in `WorkflowList.tsx` so that the unnecessary duplication of an object (which contains text for display previously including the word "workflow") could be fixed.
  - Fixed the incorrect typing of a function as uncovered by these changes.

### What was not done:
- Updating the language used in the Export to Workspace modal (see images below). Uses of the word "workflow" here refer to the workflow being created in a workspace, not the method in the Methods Repo from which it is created.
main export to workspace modal image
post-export export to workspace modal image

- Updating any other internal use of the word "workflow" in the Broad Methods Repo code. In general, all directory names, file names, and identifiers (component names, constants, etc.) that previously used the word "workflow," as well as most other internal wording not specifically referring to UI elements now using the word "method," still use the word "workflow" rather than "method." Internal nav path identifiers were also not changed, although the URL paths they correspond to were updated.

### Why
- To help differentiate between methods in the methods repo and runnable workflows in workspaces by changing user-facing language.
- To reduce confusion for users accustomed to the terminology used in Firecloud UI's implementation of the Broad Methods Repo.

### Testing strategy
- [x] Manual testing (checked that the word "workflow" is not visible anywhere where it should not be)
- [x] Searched for instances of the word "workflow" in the methods repo files to ensure that all remaining usages are expected
- [x] Updated existing unit tests

### Visual aids

Main methods repo page:
main methods repo page image

Method details page:
method details page image

### CODE REVIEW

**Comment by salonishah11** [comment]
@sam-schu Would it be possible to also rename the internal files and components to refer to `Methods` instead of `Workflows`? It would be better to keep it all consistent. This will also avoid the questions/discussion that might come up in future regarding why the file still refers to Workflows and UI displays Methods. It will also differentiate these methods repo files from already existing Workflows related files (workflows app, workflows tab inside workspace, etc)

**Comment by sam-schu** [comment]
> @sam-schu Would it be possible to also rename the internal files and components to refer to `Methods` instead of `Workflows`? It would be better to keep it all consistent. This will also avoid the questions/discussion that might come up in future regarding why the file still refers to Workflows and UI displays Methods. It will also differentiate these methods repo files from already existing Workflows related files (workflows app, workflows tab inside workspace, etc)

@salonishah11 In regards to differentiating the methods repo files from other workflows-related files, the new directory structure/file organization in [AN-160](https://broadworkbench.atlassian.net/browse/AN-160) should help with this, and I am planning to rename `src/pages/workflows` to `src/pages/methods-repo` and add a new `src/workflows/methods-repo` components directory. I could rename all the files and components to use "Methods" rather than "Workflows," but this would require also changing numerous variable names, comments, etc. in all those files for full consistency, which I am worried might add hundreds of additional changes that could pollute the `git blame`. Please let me know what you think.

[AN-160]: https://broadworkbench.atlassian.net/browse/AN-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by salonishah11** [comment]
@sam-schu I see your point.  I understand that it would be non-trivial to changw all variable names, individual comments, etc. What about changing only file names and top level components?

**Comment by sam-schu** [comment]
@salonishah11 I can do that. How do we feel about keeping this PR to user-facing changes and adding the renames to [AN-160](https://broadworkbench.atlassian.net/browse/AN-160), which touches a similar set of files, so that all the file moves and renames (internal organization changes) are done together?

[AN-160]: https://broadworkbench.atlassian.net/browse/AN-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by salonishah11** [comment]
@sam-schu that sounds fair 👍

**Review by lucymcnatt — APPROVED** [review]
LGTM! Tested on my BEE as well and everything checks out

**Review by salonishah11 — APPROVED** [review]

**Comment by sam-schu** [comment]
@lucymcnatt Saloni and I were discussing further on Slack, and she decided that she would prefer to leave the file and component names as is for now since we are not updating other internal naming, so that at least all the internal wording is consistent with itself. How do you feel about this?

**Comment by lucymcnatt** [comment]
> since we are not updating other internal naming, so that at least all the internal wording is consistent with itself

Makes sense to me! separation of concerns and all that

**Pull request merged**
