### PR TITLE
update react-scripts

### PR DESCRIPTION
**Pull request by zarsky-broad**
This is a major update.

**Why is this high risk?**
Simply because it touches everything involved in our build process. In theory, react-scripts 2 should be a [(more or less)](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#breaking-changes) drop-in upgrade. However, this is complicated because we use react-app-rewired to override some behavior. Officially, react-app-rewired [does not support react-scripts 2](https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507), and an alternative is being developed by some of the community. However, we use only very basic rewires to touch the webpack and eslint configs, and these still work. Still, if we were breaking the create-react-app promise before, we're positively *wrecking* it now.

**Pros**
- Allows using new react-scripts features, like updated webpack and eslint
  - New webpack is supposed to be a great deal faster.

**Cons**
- It wasn't broken, and yet we're trying to fix it.

### CODE REVIEW

**Comment by panentheos** [comment]
Click tested and everything looks good. Can you please add some documentation of why this is high risk, and list the pros and cons?

**Comment by katevoss** [comment]
@zarsky-broad how would I test this? What should I be on the lookout for?

**Comment by zarsky-broad** [comment]
@katevoss literally everything. But basically, if all the parts still load on the PR site, we're good

**Review by katevoss — APPROVED** [review]
I too clicked around a while and it looks good to me!

**Review by panentheos — APPROVED** [review]

**Pull request merged**
