### PR TITLE
IA-3864  Only read apps that has `saturnAutoCreated` label apps similar to runtimes

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3864

Tested out the change locally, and I'm able to load cloud env page properly now. VS, on dev, cloud env fail to load because it tries to load apps created outside terra UI as well

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

### CODE REVIEW

**Comment by n8landolt** [comment]
reading the ticket, Environments.js line 479 needs to be updated:

```    
const { appName, diskName, auditInfo: { creator }, workspace: { workspaceId, googleProject } = {} } = app
```

Otherwise if you've created an app from the swagger/API you'll get:

Cannot read properties of undefined (reading 'workspaceId')

on the cloud environments page.

**Comment by Qi77Qi** [comment]
@n8landolt  I think that's the direct cause for the error in UI...but I think we shouldn't expect apps being retrieved without `saturnAutoCreated` label to begin with

**Comment by n8landolt** [comment]
Do we want to do the same change with Disks? I can currently see my Galaxy disk but not runtime created from the API

**Comment by Qi77Qi** [comment]
@n8landolt ah good point. Will follow up on that. But we won't be able to do that for disks until some Leo DB migration has happened(need to make sure all disks created by terra has the label). So I think we should do that in a separate PR

**Review by n8landolt — APPROVED** [review]

**Review by lucymcnatt — APPROVED** [review]

**Pull request merged**
