### PR TITLE
[WM-1738] Method Details - Configuration tab

### PR DESCRIPTION
**Pull request by kpierre13**
### What
- Getting the Configurations tab in Terra UI to function similarly to FC-UI
From the ticket:
- [x] Implement filter box
- [x] Fix text overflow in Configuration box
- [x] Columns resizable
- [x] First columns is an incompatibility warning (did not remove)

### Why
- Migrating functionality from FC-UI to Terra UI

### Testing strategy

- [x] unit tests

https://github.com/user-attachments/assets/dd0a22f4-2382-421a-a239-603e03e70144

### CODE REVIEW

**Review by aednichols — APPROVED** [review]
Clicked around with my test account and LGTM 👍

**Comment by salonishah11** [comment]
It seems by default there is lot of space on the right side of the table. @kpierre13 would it be easy to make the table occupy the whole width of the screen with each column getting right amount of column width?

Screenshot 2024-07-30 at 11 38 56 AM

**Comment by kpierre13** [comment]
> It seems by default there is lot of space on the right side of the table. @kpierre13 would it be easy to make the table occupy the whole width of the screen with each column getting right amount of column width?

@salonishah11 It seems like since we're using a `GridTable` here, the column widths need to be [explicitly stated](https://github.com/DataBiosphere/terra-ui/blob/05f8ddca4adf9297585972210aa8c43c38c2ec54/src/components/table.js#L491-L494). I can definitely try and find the correct ratio for the table, but that would only adhere to my specific screen, and may be too large for a smaller screen. I think that's the tradeoff here with `GridTable` vs. `FlexTable`.

**Comment by salonishah11** [comment]
Ah its GridTable. Yeah that needs fixed width and I think to make the columns resizable you need to use GridTable which makes it incompatible with having columns fill up space dynamically. This is bringing back memories. Yeah in this case it makes sense to leave it as what you have. If you like you can increase width for Configuration and Synopsis but its up to you.

**Review by salonishah11 — APPROVED** [review]

**Pull request merged**
