### PR TITLE
Update release note link (BW-1073).

### PR DESCRIPTION
**Pull request by cahrens**
Accessible through the "hamburger" menu on the left side.

image

### CODE REVIEW

**Review by cjllanwarne — APPROVED** [review]

**Review by kyuksel — APPROVED** [review]
Should we also set an annual Slack reminder or something to do this at the beginning of a year? I assume there's a reason why there can't be an alias link maintained by User Ed so we wouldn't need to change anything.

**Comment by cahrens** [comment]
@kyuksel I decided it was just easiest to go ahead change the URL, but it is possible that user ed can maintain a link. I will post in their Slack channel to see.

**Comment by cahrens** [comment]
I posted in Slack (https://broadinstitute.slack.com/archives/CE99R8RD5/p1644241543244199), but I think I'll go ahead and merge this in the meantime. It's easy enough to change the URL again if they set up an alias.

**Comment by kyuksel** [comment]
@cahrens Sorry that my comment wasn't clear. I was agreeing with merging this PR. My suggestions were to make it less easy to miss subsequent annual updates.

**Pull request merged**
