### PR TITLE
Add automated security scans on dev environment

### PR DESCRIPTION
**Pull request by adrazhi**
This PR introduces automated security scans in terra-ui [dev environment](https://bvdp-saturn-dev.appspot.com). 

Only fail on error code 1, which indicates at least one FAIL was found. Error codes 2 & 3 indicate WARN or other, and should not break the run. 

_Note:_ Lightweight prod scans will be setup in the future. For now it's dev only.

### CODE REVIEW

**Review by zarsky-broad — CHANGES_REQUESTED** [review]
Can you start by matching the old indentation?

**Comment by adrazhi** [comment]
> Can you start by matching the old indentation?

Oops, sorry, I'll fix that.

**Comment by adrazhi** [comment]
@zarsky-broad Should be matching the original indentation now. Not sure what got it messed up. Thanks!

**Comment by zarsky-broad** [comment]
I'm still seeing a bunch of indentation changes...?

**Comment by adrazhi** [comment]
@zarsky-broad I started fresh from original file this time. Does it seem ok?

**Comment by zarsky-broad** [comment]
The GitHub diff still shows indentation changes. I think the auto-indent in your IDE may be to blame.

**Review by zarsky-broad — APPROVED** [review]

**Comment by zarsky-broad** [comment]
Thanks for fighting through the indentation, feel free to merge and delete the branch!

**Pull request merged**
