### PR TITLE
[SU-260] Allow renaming files from file browser

### PR DESCRIPTION
**Pull request by nawatts**
https://broadworkbench.atlassian.net/browse/SU-260

Stacked on #4078.

This adds the UI for renaming files from the file browser.

https://github.com/DataBiosphere/terra-ui/assets/1156625/afa65e8e-dac5-44bc-89f6-e6a3d87fa423

### CODE REVIEW

**Comment by calypsomatic** [comment]
Is this for just Azure?  I tried testing it out and in GCP the three-dots menu did not appear for the files.

**Comment by nawatts** [comment]
For GCP, which file browser did you use?

Screenshot 2023-07-27 at 10 20 54 AM

The new file browser has to be enabled for GCP workspaces from the feature preview page (https://bvdp-saturn-dev.appspot.com/#feature-preview). Azure workspaces only use the new file browser.

**Comment by calypsomatic** [comment]
> For GCP, which file browser did you use?
> The new file browser has to be enabled for GCP workspaces from the feature preview page (https://bvdp-saturn-dev.appspot.com/#feature-preview). Azure workspaces only use the new file browser.
Aha!  That was it.  Thank you!

**Comment by nawatts** [comment]
This button should be disabled / show a tooltip if the user doesn't have permission to write to the workspace.

**Comment by nawatts** [comment]
The rename button should be disabled / show a tooltip if the user doesn't have permission to write to the workspace.

**Review by calypsomatic — APPROVED** [review]

**Comment by nawatts** [comment]
Rebased after rebasing #4078 to resolve merge conflicts.

**Review by yuliadub — APPROVED** [review]

**Comment by yuliadub** [comment]
I am not sure why, but it took me a second to fine the rename in the ... dots -> for some reason a more intuitive way I was expecting was to select the file and see "Rename" appear next to the "New folder" button. I dont think anything needs to be changed, but just wanted to leave this here since it came to mind :)

**Comment by nawatts** [comment]
Generally, the buttons at the top of the file browser either create a new file/folder (upload / new folder) or operate on a list of files (delete). But rename doesn't make sense as an operation on multiple selected files, so I had to add the menu for operations on a single file. The 3 dots button on the side was based on the UI in other lists (workspaces, groups, etc).

**Pull request merged**
