### PR TITLE
[UIE-89] move analysis components

### PR DESCRIPTION
**Pull request by msilva-broad**
## Summary of changes:
Analysis related UI components and modules moved to new feature-area based project organization.  Files, subfolders, moved to src/analysis/...

### What
- file moves, import cleanup

### Why
- in preparation for further cleanup to support UI Code Sharing effort (and general code organization improvements).  This will better align things for eventual split up into sub-packages within a mono-repo setup.

### Testing strategy
- basic smoke test... no functional changes, just file folder location shift

### CODE REVIEW

**Review by blakery — APPROVED** [review]
yup, looks like it's all moving things and rearranging imports

**Comment by cahrens** [comment]
Don't forget to update the CODEOWNERS file.

**Comment by msilva-broad** [comment]
> Don't forget to update the CODEOWNERS file.

I was gonna do that as a quick follow, just to get these hard-to-remerge file moves in a bit quicker.

**Review by jdcanas — APPROVED** [review]
Is it worth putting the visual components (i.e. `Environments.js` and `ContextBar.js`) and the hooks (`useAnalysisFiles` and `useRuntimes`) in their own folders?

**Comment by msilva-broad** [comment]
> Is it worth putting the visual components (i.e. `Environments.js` and `ContextBar.js`) and the hooks (`useAnalysisFiles` and `useRuntimes`) in their own folders?

probably... but that can be an iterative (and much smaller) PR after this one :)

**Pull request merged**
