### PR TITLE
[DR-2170] Updated displayed text

### PR DESCRIPTION
**Pull request by lu-c**
Changing wording of the button text. Removed files/filesize display.

### CODE REVIEW

**Review by petesantos — APPROVED** [review]

**Comment by kyuksel** [comment]
FYI @lu-c that the CI build…

image

**Comment by kyuksel** [comment]
@lu-c FYI that you already have your Terra UI Code Owners 👍🏼 . You just need another 👍🏼 (from someone who ideally knows about the domain and can do manual testing, e.g. a teammate) to merge.

**Comment by lu-c** [comment]
> @lu-c FYI that you already have your Terra UI Code Owners 👍🏼 . You just need another 👍🏼 (from someone who ideally knows about the domain and can do manual testing, e.g. a teammate) to merge.

Oh haha, Pete must be a Terra UI Code owner!  He is also a teammate, who knows the context for the PR and the customer request. At the moment, I'm just looking for another secondary approval, which can be from anyone. I'll let my team know too

**Comment by kyuksel** [comment]
> Oh haha, Pete must be a Terra UI Code owner!

He is :)

> He is also a teammate, who knows the context for the PR and the customer request. At the moment, I'm just looking for another secondary approval, which can be from anyone. I'll let my team know too

Gotcha. Yea, asking your team makes a lot of sense. If your team is short-handed or something, you could also post on #terra-ui-champions Slack channel.

**Review by tcjiang9 — APPROVED** [review]

**Pull request merged**
