### PR TITLE
[UIE-120] Use Terra-ui useThemeFromContext instead of colors

### PR DESCRIPTION
**Pull request by evrii**
### What
- Replaced src/libs/colors with useThemeFromContext from @terra-ui-packages/components

### Why
- I am working on porting notifications to packages.

### Testing strategy
- [ ]

### CODE REVIEW

**Review by nawatts — COMMENTED** [review]
It looks like this also contains changes from another PR: #4601

**Comment by evrii** [comment]
> It looks like this also contains changes from another PR: #4601

Yeah, I made this branch off of the branch in that PR (since it's the same file) while I was waiting for the other to get approved.

**Comment by nawatts** [comment]
FYI, if you don't want the other PR's changes to show up in the diff here, you can set this PR's base branch to the other PR's branch.

**Comment by evrii** [comment]
> FYI, if you don't want the other PR's changes to show up in the diff here, you can set this PR's base branch to the other PR's branch.

Thank you. That's a great suggestion.

**Review by nawatts — APPROVED** [review]

**Review by jdcanas — APPROVED** [review]

**Pull request merged**
