### PR TITLE
[UIE-160] Check for missing cache files in CI

### PR DESCRIPTION
**Pull request by nawatts**
Every once in a while, a PR updates dependencies without updating the Yarn cache. For example, most recently, #4680 (and the associated cleanup, #4704). This causes confusion for developers when they later run `yarn install` and find untracked files and often results in noise in PRs if the cache files are committed along with other unrelated changes.

This adds to the `build` CI job a check for missing cache files. This will prevent merging a PR unless the Yarn cache is up to date.

Note, that we used to effectively have this check by running `yarn install --immutable-cache` in CI. However, we had to remove that when we added Pact because the cache file for one of the Pact packages exceeds GitHub's file size limit (see #4138).

### CODE REVIEW

**Comment by nawatts** [comment]
Note, `build` is expected to fail on this PR until #4704 is merged.

**Review by jdcanas — APPROVED** [review]

**Review by pshapiro4broad — APPROVED** [review]
Seems like a good idea. Would it be too expensive (or just a bad idea) to do this as a precommit check? If I can find out before the PR build that I made a mistake that'd be nice.

**Comment by cahrens** [comment]
@nawatts how will this not fail in the pact case?

**Comment by nawatts** [comment]
> how will this not fail in the pact case?

Since the cache file for `@pact-foundation/pact-core` is ignored in `.gitignore`, it won't show up as an untracked file. 
https://github.com/DataBiosphere/terra-ui/blob/3215fec9d52a9481e9d60ff5e0afef475e0e3ff5/.gitignore#L53-L54

**Comment by nawatts** [comment]
>  Would it be too expensive (or just a bad idea) to do this as a precommit check? If I can find out before the PR build that I made a mistake that'd be nice.

This same check could be added to the pre-commit hook. However, that wouldn't catch cases where `yarn install` wasn't run (and thus the cache not updated). And `yarn install` takes long enough I'm not keen on adding that to pre-commit.

**Comment by cahrens** [comment]
@nawatts the missing cache files were added with https://github.com/DataBiosphere/terra-ui/pull/4706, so you should be able to update this branch and proceed.

**Comment by nawatts** [comment]
Looks like #4706 only added two out of the three missing cache files. Running `yarn install` still generates an untracked file `.yarn/cache/@pact-foundation-pact-npm-12.1.1-66cd761533-3ed709cab7.zip`.

**Comment by nawatts** [comment]
Added the remaining cache file to this PR in https://github.com/DataBiosphere/terra-ui/pull/4708/commits/52ee50e56e7f7626f36ba82f57e0526978bcca07.

**Comment by cahrens** [comment]
> Looks like #4706 only added two out of the three missing cache files. Running `yarn install` still generates an untracked file `.yarn/cache/@pact-foundation-pact-npm-12.1.1-66cd761533-3ed709cab7.zip`.

I thought that one was the pact file that we intentionally didn't check in… didn't notice the slight difference in name. Thanks for adding it!

**Comment by nawatts** [comment]
The one that we intentionally omit is for `@pact-foundation/pact-core`, not `@pact-foundation/pact`. Since the pact-core cache file is ignored, it never appears as an untracked file.

**Pull request merged**
