### PR TITLE
Allow some calls to not have start dates [BW-712]

### PR DESCRIPTION
**Pull request by cjllanwarne**
Tested locally with a "recreation" workflow on `dev`: http://localhost:3000/#workspaces/general-dev-billing-account/cjl_test_workspace/job_history/0236a12b-0af0-46c1-a8f7-8f5d5cc1b99a/74d8ac0f-024e-4950-b93a-de447b44829c

### CODE REVIEW

**Comment by breilly2** [comment]
@cjllanwarne I'd like to quickly test this for myself (I didn't fully test the code I suggested). Could you share your test workspace with breilly.firecloud@gmail.com?

**Review by dmohs — APPROVED** [review]
👍  code style. Did not test.

**Review by salonishah11 — APPROVED** [review]
LGTM. Tested the code using above mentioned submission.

**Comment by cjllanwarne** [comment]
@breilly2 you should now have access to the workspace 🤞

**Pull request merged**
