### PR TITLE
[DC-876] Update to use new SnapshotBuilderSettings

### PR DESCRIPTION
**Pull request by s-rubenstein**
### Jira Ticket: https://broadworkbench.atlassian.net/browse/dc-876

This change should follow shortly after https://github.com/DataBiosphere/jade-data-repo/pull/1615, which makes the breaking API change on the DataRepo side. This only works because we have not yet publicly released the Cohort Builder

## Summary of changes:
This updates the SnapshotBuilderSettings object to include the min/max and values information. This enables us to streamline our API calls to improve loading performance.

### What
- 

### Why
- 

### Testing strategy
- [ ]

### CODE REVIEW

**Review by snf2ye — APPROVED** [review]
It's great that this change has simplified the UI code so much!

**Comment by s-rubenstein** [comment]
https://github.com/DataBiosphere/terra-ui/assets/15351021/e979772c-c2d6-4561-9689-0da5e5058a30

**Review by rjohanek — APPROVED** [review]
Changes look good and thanks for the video! One more question, it's not in the video - does this still work for the list options as well?

**Comment by s-rubenstein** [comment]
@raejohanek it does, but it errors first, because of the list empty bug.

**Pull request merged**
