### PR TITLE
[WX-1721] Workflow options settings in GCP workspaces are persisted in local storage

### PR DESCRIPTION
**Pull request by salonishah11**
### What
- Non-default Workflow options in Submission Configuration page in GCP workspaces will now be saved to local storage. The workflow options are persisted per user per workspace. 
- The key pattern is similar to what exists in Terra UI: `dynamic-storage/<user-id>/<workspace-namespace>/<workspace-name>/workflow_options`

### Why
- To reduce the cognitive overload for a user when they are configuring their submission

### Testing strategy

- [x] tested locally
- [x] unit tests

### Visual Aids 

Initial state of local storage:
Screenshot 2024-07-23 at 5 18 13 PM

---

When non-default workflow options are selected, they are updated in local storage:
Screenshot 2024-07-23 at 5 19 01 PM

---

When non-default workflow options are unchecked, the key is removed from local storage:
Screenshot 2024-07-23 at 5 21 05 PM

---
Workflow options in local storage from 2 different workspaces:
Screenshot 2024-07-23 at 5 29 03 PM

### CODE REVIEW

**Review by THWiseman — COMMENTED** [review]
LGTM! Thanks for the find & fix

**Review by THWiseman — APPROVED** [review]

**Review by aednichols — COMMENTED** [review]
Found one edge case.

1. Load a fresh workspace
2. Uncheck call caching
3. Reload page

Expected result:
Call caching remains unchecked

Actual result:
Call caching is checked

**Comment by salonishah11** [comment]
@aednichols @THWiseman persisting of call caching option (when it is disabled) has been added in [this commit](https://github.com/DataBiosphere/terra-ui/pull/4964/commits/1c561e898e2d2b5932e580ec3e03afa03c65a92d)

**Review by aednichols — APPROVED** [review]
Tested in PR environment, looks good to me 👍

**Review by THWiseman — APPROVED** [review]

**Comment by salonishah11** [comment]
The 4 SonarCloud issues are related to missing props validation. It was non-trivial to fix those issues and after few attempts to fix it, missing props validation at other places was detected by SonarCloud when I attempted to refactor `WorkflowView` class. Since the way to get namespace and name from props is based on current pattern in the class I am merging this PR as is and it can be refactored later.

**Pull request merged**
