### PR TITLE
[DC-102] Expanding unit tests a little

### PR DESCRIPTION
**Pull request by lu-c**
Added unit testing for multiple facets and the clear button

### CODE REVIEW

**Review by petesantos — APPROVED** [review]
LGTM!

**Review by petesantos — COMMENTED** [review]
For compliance reasons I think all of our PR's need a ticket

**Review by fboulnois — APPROVED** [review]
lgtm! As Pete says, please associate this PR with a ticket before merging.

**Comment by lu-c** [comment]
Just edited this title to tack it onto the DC-102 ticket (addressing search and filtering)

**Pull request merged**
