### PR TITLE
[IA-3807] Removed analysis-context-bar from dev and staging environment tests.

### PR DESCRIPTION
**Pull request by n8landolt**
https://broadworkbench.atlassian.net/browse/IA-3807

### CODE REVIEW

**Comment by n8landolt** [comment]
Where should we document best practice for making change to ContextBar.js? We'll want to run this analysis-context-bar.js on PRs that touch the component.
My thoughts:
1. Add a comment in the ContextBar.js file.
2. Add checklist into PRs
3. Add into Contributing.md

For the time being I'm comfortable with ContextBar.js comment.

**Review by cahrens — APPROVED** [review]

**Comment by cahrens** [comment]
I think a comment in ContextBar.js and adopting this as a best practice on your team is probably good enough at this point. I don't think something this file-specific belongs on a PR checklist or on Contributing.md.

**Comment by cahrens** [comment]
Got another failure: https://app.circleci.com/pipelines/github/DataBiosphere/terra-ui/12595/workflows/c2e79ea8-4d23-4919-9195-4a9a8a42507c/jobs/52410

**Comment by cahrens** [comment]
And again: https://app.circleci.com/pipelines/github/DataBiosphere/terra-ui/12600/workflows/3af7cfd9-fd45-429b-88ad-69c010c214f2/jobs/52425

@n8landolt can you get a second reviewer from your team?

**Review by nawatts — APPROVED** [review]

**Comment by cahrens** [comment]
Another failure: https://app.circleci.com/pipelines/github/DataBiosphere/terra-ui/12640/workflows/14da6c6d-4a6b-4676-9145-2aae179e30e8/jobs/52529

**Review by xuscrbw — APPROVED** [review]
lgtm

**Pull request merged**
