### PR TITLE
Fix url for call_interval_list in Hg38 Reference Table

### PR DESCRIPTION
**Pull request by ehanna4**
ticket: https://broadworkbench.atlassian.net/browse/SUP-226

### CODE REVIEW

**Review by panentheos — APPROVED** [review]
Looks good.

It might be worth communicating that because this data gets copied to the workspace, anyone who previously added it would need to remove and re-add it in order to see the change.

**Comment by zarsky-broad** [comment]
Do they even have to remove first? Or does adding overwrite?

**Comment by ehanna4** [comment]
They do have to re-import it to see the updated link. How/where should I communicate this? In the Suggested Release Notes?

**Comment by zarsky-broad** [comment]
That's the best idea I can think of, yeah

**Pull request merged**
