### PR TITLE
AJ-829 Indicate TSV upload is in progress

### PR DESCRIPTION
**Pull request by calypsomatic**
See [AJ-829](https://broadworkbench.atlassian.net/browse/AJ-829)
Previously, while a large TSV was uploading, the upload modal would remain opening until processing finished, giving no indication that anything was happening.  
This PR makes use of the 'Data import is in progress' notification to indicate upload is in progress.   A 'Data import in progress' notification will pop up for files of moderate size; a success notification for all files.

Before this PR:
image
After:
image

Other changes:
- Removes 'Add data to this workspace' tooltip that was remaining open over import button
- Updates wording when WDS is loading to be more general.

Note: this PR has gone through many iterations; please ignore conversations from before 3/1/23 as they are no longer relevant.

[AJ-829]: https://broadworkbench.atlassian.net/browse/AJ-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cahrens** [comment]
This is a pretty different pattern from how we normally show something like this. Typically there would be a spinner over the page or a region of it, or perhaps over the dialog-- I don't think I've ever seen the button itself replace its text with a spinner. Did you touch base with UX about this pattern?

**Comment by calypsomatic** [comment]
> This is a pretty different pattern from how we normally show something like this. Typically there would be a spinner over the page or a region of it, or perhaps over the dialog-- I don't think I've ever seen the button itself replace its text with a spinner. Did you touch base with UX about this pattern?

@cahrens No, I admit I took it as just a quick fix!  Sounds like our UX person is on vacation now, but will run it by PM for at least some more promising ideas.  Also welcome any suggestions that you might have!

**Comment by cahrens** [comment]
Perhaps search the codebase for other places where something is uploaded in a dialog. For instance, `SupportRequest` (though I think that UX is quite old).

**Comment by cahrens** [comment]
Also probably good to see what the `FileBrowser` does, as that is new code. I think it may use `ProgressBar`.

**Review by aaronkanzer — APPROVED** [review]

**Review by jordansafer — APPROVED** [review]
See attached video, there is some funny behavior:
- Mainly WDS becomes unresponsive for a large TSV, and things get funny if I switch tabs and back
- Also, the hover-over thingy for the Import Data button pops up for some reason while I'm not hovering. This happens consistently

https://user-images.githubusercontent.com/8800717/217107883-56de514b-f17c-40e3-b8cd-c964551148e3.mov

**Comment by calypsomatic** [comment]
> See attached video, there is some funny behavior:
> 
> * Mainly WDS becomes unresponsive for a large TSV, and things get funny if I switch tabs and back
> * Also, the hover-over thingy for the Import Data button pops up for some reason while I'm not hovering. This happens consistently
> 
>  uploadtsv.mov

@jordansafer This behavior seems to be present before my changes - if you click outside the upload modal (or click the misleading Cancel button) then the hover-over thing pops up, and you can move to another tab and back and see the troubleshoot link with the same results.  I guess having the upload modal remain open simply discourages users from doing so, which I think is probably better UX, but maybe there's other issues here.

**Comment by msilva-broad** [comment]
> > This is a pretty different pattern from how we normally show something like this. Typically there would be a spinner over the page or a region of it, or perhaps over the dialog-- I don't think I've ever seen the button itself replace its text with a spinner. Did you touch base with UX about this pattern?
> 
> @cahrens No, I admit I took it as just a quick fix! Sounds like our UX person is on vacation now, but will run it by PM for at least some more promising ideas. Also welcome any suggestions that you might have!

I think a key goal of having a larger splash-area spinner is often to prevent the user from continuing to interact with the form/modal inputs while we have a "submit" operation in-flight.  This is good for throttling and preventing system spamming, and also simplifying away edge-cases that would come with allowing continued input interactions in the UI>

**Pull request closed without merging**
