### PR TITLE
Open external links from EULA and Privacy Policy in a new window

### LINKED ISSUE #1537: when someone agrees to Free Credits agreement, open links in a new window
When a new user clicks "Start Trial", they have a 2 page agreement to agree to. This includes many external links, which all open in the same window. Those links should open in a new tab so the user's flow is not interrupted.

### PR DESCRIPTION
**Pull request by breilly2**
Closes: #1537 

We could consider making this more global. Since we can look at `href`, we can make decisions about whether or not its an external link (I suspect we'd have little reason to put internal links in markdown, but maybe we would at some point). Before doing that, however, I'd want to make sure it's not hackable in other contexts (specifically workspace description).

### CODE REVIEW

**Review by zarsky-broad — APPROVED** [review]
My only thought is that the name should in some way indicate that it's intended for markdown, and not for more general use.

**Comment by breilly2** [comment]
@zarsky-broad Would you have any objection to me extracting `Markdown` and `newWindowLinkRenderer` into a new `Markdown.js` and not renaming the function? Would that address your concern (that I also share)?

**Comment by zarsky-broad** [comment]
That sounds much neater.

**Review by panentheos — APPROVED** [review]
Looks good.

**Pull request merged**
