### PR TITLE
change agora to Firecloud methods repository

### LINKED ISSUE #959: On tool cards, change "source: agora" to "source: FireCloud Methods Repository"
Our tool cards reference agora, which is a microservice name that does not have meaning to users:

Change the link name from "agora" to "FireCloud Methods Repository"

### PR DESCRIPTION
**Pull request by panentheos**
Fixes #959

### CODE REVIEW

**Review by zarsky-broad — APPROVED** [review]

**Comment by breilly2** [comment]
I'm not loving how the length of the text affects the layout. Assuming it fits, I'd rather the entirety of "FireCloud Methods Repository" be on one line below "Source:" (which should then also be done with "dockstore" for consistency, which itself should probably be rendered as "Dockstore" for consistency) or indent by the width of "Source:" when wrapping.

screen shot 2018-12-07 at 1 26 31 pm

**Review by elizzhao — APPROVED** [review]
does the thing, but I agree it looks a little awkward on two lines

**Review by katevoss — COMMENTED** [review]
I agree that the 2 line break isn't idea, plus when the tools are in list form it takes up 3 lines:
screen shot 2018-12-07 at 4 57 38 pm

**Comment by panentheos** [comment]
Thanks for the feedback. I changed the name to just 'FireCloud' for now, which eliminates the formatting problems. If we want the longer name, we can rethink the design a bit.

**Review by breilly2 — APPROVED** [review]
👍

**Pull request merged**
