### PR TITLE
[WX-1533] Add filter capability to Submission History page

### PR DESCRIPTION
**Pull request by rsaperst**
### What
- Add dropdown to filter by workflow Success or Failure on Submission History page
- Change wording of filter dropdown on Submission Details page from "Error" to "Failure"
- Slightly modify styling of Submission Details page so that the filter component can be used across both pages

### Why
- This feature will make the Submission History page easier to use in workspaces where many workflows have been run and users only want to see workflows that failed or only workflows that succeeded

### Testing strategy

- Automated testing 
- Manual testing on UI

Submission History Page:
Screenshot 2024-05-13 at 4 39 51 PM

Submission Details Page:
Screenshot 2024-05-13 at 4 40 08 PM

### CODE REVIEW

**Comment by aednichols** [comment]
The feature works well, tested on PR environment. I am concerned that we are eating even more of the user content area with our chrome though. It would be great if we could put "Filter by" and the dropdown on the same line, and maybe even delete the "Submission history" title & blurb (do we need it in both the sidebar and the main area?).

On a 1280x800 display, the content drops from 31% of the total browser window:



To 22%:

**Comment by aednichols** [comment]
I just noticed that the Status cell in the header already supports sorting by status, which feels deeply related to filtering. If you really want to shoot the moon on space efficiency you could put it there. Obviously subject to the test of, "would a reasonable user figure this out?".

**Comment by rsaperst** [comment]
> The feature works well, tested on PR environment. I am concerned that we are eating even more of the user content area with our chrome though. It would be great if we could put "Filter by" and the dropdown on the same line, and maybe even delete the "Submission history" title & blurb (do we need it in both the sidebar and the main area?).

I updated the styling to put the "Filter by" and dropdown and "Submission History" on the same line -- I talked with Sara and she wanted to keep the title to be consistent with other pages and she thought this was the best style. I updated the summary of this PR with a new screenshot if you want to see what this looks like.

**Review by aednichols — APPROVED** [review]
Updated design looks good IMO. I'm not the most knowledgable UI reviewer, but code seems reasonable.

**Review by jgainerdewar — APPROVED** [review]

**Pull request merged**
