### PR TITLE
Add Feature Request and Community Discussion to Left nav

### LINKED ISSUE #1245: Change integration point with support center
We currently have a link to our docs and support page called "Terra support". We should keep this link but change the language to "Learn about Terra". We should add two additional links:
*  "Request a feature" (ask Lou for an icon): points to https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500452-Feature-Requests
* "Community discussion" (ask Lou for icon): points to https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500432-General-Discussion

### PR DESCRIPTION
**Pull request by katevoss**
Fixes #1245 

Any feedback on the icons? @lstrano-broad @bradtaylor @jeromechadel 
screen shot 2019-03-04 at 5 21 11 pm

### CODE REVIEW

**Comment by lstrano-broad** [comment]
icons look good - thx!

**Comment by jeromechadel** [comment]
I’m ok with the icons as well. 
Once you are in the Terra Support website, I don’t see a way of going back to Terra. 
Could the Terra logo serve that purpose? 
Thank you,

Jerome

**Comment by katevoss** [comment]
That's a good idea @jeromechadel, @tmm211 do you know if it's possible to add a link from the Terra Support site (on Zendesk) back to Terra?

Also, note that each of the support links, "Learn about Terra", "Request a feature", and "Community discussion", open in a new tab in the browser so the user is not actually directed off of Terra. They have it open in the prior browser tab.

**Review by zarsky-broad — APPROVED** [review]

**Comment by tmm211** [comment]
Yes, we can do that...where makes sense?

**Pull request merged**
