### PR TITLE
Updating a cluster now calls the leo update endpoint when appropriate instead of always re-creating

### PR DESCRIPTION
**Pull request by jdcanas**
This PR allows the ClusterManager to call PATCH to change resources in certain scenarios, over needing to create a new cluster in all scenarios.

There is a [diagram](https://drive.google.com/open?id=1mtFFecpQTkGYWSgPlaHksYaIudWHa0dY) to describe what scenarios result in

1. a Stop -> update -> Stop
2. a dynamic update
3. a re-create

The variations are there because of google cloud api limitations in most cases.

Requesting a preliminary code review while the diagram/workflow is under review.

### CODE REVIEW

**Comment by zarsky-broad** [comment]
You should start by resolving the conflicts, this'll be a lot easier to review after that 🙇

**Comment by zarsky-broad** [comment]
There seem to be a bunch of instances where intellij's autoformat seems to have chopped something that was happy on one line into multiple. We should undo these.

**Comment by kleighwe** [comment]
@panentheos Can you comment here why this is on hold? That'll make it easier to track later, thanks! :)

**Comment by panentheos** [comment]
Actually I think we're taking a different path after some discussions. @jdcanas are you ok with closing this PR? (We can keep the branch around if it's helpful)

**Comment by panentheos** [comment]
Closing for now, since we needed to rethink the approach here.

**Pull request closed without merging**
