### PR TITLE
library fixes

### PR DESCRIPTION
**Pull request by zarsky-broad**

### CODE REVIEW

**Review by breilly2 — COMMENTED** [review]
I don't understand the `flex` to `width` change but the rest makes sense. Probably want to wait for another thumb.

**Comment by zarsky-broad** [comment]
@breilly2 That was just me realizing it was a less convoluted way to write it.

**Review by elizzhao — APPROVED** [review]
looks good!

**Comment by MattPutnam** [comment]
I get an error on trying to from the workspaces list (presumably anywhere) to the library pages:

TypeError: Cannot read property 'hideNav' of undefined

Pointing to TopBar.js:85

**Comment by MattPutnam** [comment]
`flex: 1` on that left panel?

screen shot 2018-12-04 at 1 21 50 pm

**Pull request merged**
