### PR TITLE
Fix error logic on workflow view [risk: low]

### PR DESCRIPTION
**Pull request by MattPutnam**
Don't know when this broke, but this restores the original behavior, plus a wording improvement.

### CODE REVIEW

**Review by zarsky-broad — APPROVED** [review]
LGTM, didn't test

**Review by elizzhao — APPROVED** [review]
Looks good!

**Comment by elizzhao** [comment]
This PR also closes #604 and #605

**Comment by katevoss** [comment]
I quickly tested it locally and it works 👍

**Review by katevoss — APPROVED** [review]

**Pull request merged**
