### PR TITLE
Update es5 to v0.10.63 Dependabot #127

### PR DESCRIPTION
**Pull request by kpierre13**
### What
- Updating dependencies

### Why
- Dependabot alert #127

### Testing strategy
- [ ] 

 

[WM-2519]: https://broadworkbench.atlassian.net/browse/WM-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mspector — APPROVED** [review]

**Review by cahrens — CHANGES_REQUESTED** [review]
We discussed this over Slack. You shouldn't hand-edit transitive library dependencies. Follow the directions in https://github.com/DataBiosphere/terra-ui/wiki/Security-and-Maintenance#dependabot-security-updates.

https://broadinstitute.slack.com/archives/C01EHNUM73R/p1709824838083479

**Comment by cahrens** [comment]
Note also that yarn cache files need to be checked in. It looks like some may have been missed in a previous update.

**Comment by kpierre13** [comment]
Replaced with PR #4706

**Comment by kpierre13** [comment]
Replaced with PR #4706

**Pull request closed without merging**
