### PR TITLE
Hide "relaunch failures" in a situation where it cannot work [WA-7]

### PR DESCRIPTION
**Pull request by aednichols**
Draft PR.

Needs https://github.com/broadinstitute/rawls/pull/1171

### CODE REVIEW

**Review by kshakir — APPROVED** [review]
LGTM

**Comment by aednichols** [comment]
Before:

Screenshot_2020-02-14 TestWorkspace-2017-05-03-10-56-49-4IFMTK-clone-a copy - Job History(1)

After:

Screenshot_2020-02-14 TestWorkspace-2017-05-03-10-56-49-4IFMTK-clone-a copy - Job History

**Comment by aednichols** [comment]
Rawls has merged, un-drafting.

AC:
- "Relaunch" hidden when config is deleted (has random chars appended)
- "Relaunch"  continues to show on latest config

Before:

Screenshot_2020-02-14 TestWorkspace-2017-05-03-10-56-49-4IFMTK-clone-a copy - Job History(2)

After:

Screenshot_2020-02-14 TestWorkspace-2017-05-03-10-56-49-4IFMTK-clone-a copy - Job History(3)

**Review by breilly2 — APPROVED** [review]
👍 Looks good! I tested by looking at a workspace with multiple submission failures on both dev and the PR site. The PR site suppressed the button in the cases that the rerun would not work.

**Comment by aednichols** [comment]
I will merge this when the Rawls change lands on Prod and I have verified it.

**Comment by breilly2** [comment]
I've concluded that this is safe to merge before the rawls change is live.

`methodConfigurationDeleted` is being destructured from an object that we know exists (it was already being destructured). If the attribute doesn’t exist, `methodConfigurationDeleted` will be `undefined`. `!methodConfigurationDeleted` will evaluate to true so the logical `&&` of that expression will have no effect.

**Pull request merged**
