### PR TITLE
[BW-748] Button order is inconsistent – confirmation button should be on the f…

### PR DESCRIPTION
**Pull request by kpierre13**
…ar right - KP_BW-748

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Review by cahrens — APPROVED** [review]
I checked out the branch and tested it-- LGTM (I'm still not at all crazy about the "Saving…" behavior, but swapping the button order doesn't make it feel worse to me).

Please do retry the tests to ensure that they are "just" flaky.

**Review by kyuksel — APPROVED** [review]
Please remember to prefix PR titles with the corresponding ticket number (e.g. BW-748) for compliance reasons.

**Comment by kpierre13** [comment]
@kyuksel I'm getting flaky test failures in circleci. The first was `run-workflow-on-snapshot` which hasn't been failing in recent reruns. The other test, 'run-notebook' is continuing to fail, so I wanted to know if this was something that is failing as a result of my changes, or if it fails because of something in dev, unrelated to this PR.

**Comment by kyuksel** [comment]
@kpierre13 Thanks for checking about this. It looks like your last rerun succeeded so this PR is good to merge 😊

**Pull request merged**
