### PR TITLE
[AJ-1075] Show Helm chart version and Docker image in WDS troubleshooter

### PR DESCRIPTION
**Pull request by nawatts**
https://broadworkbench.atlassian.net/browse/AJ-1075

Screenshot 2023-07-19 at 5 09 57 PM

### CODE REVIEW

**Comment by davidangb** [comment]
Seeing the screenshot … the "Data app image" value will be something like `us.gcr.io/broad-dsp-gcr-public/terra-workspace-data-service:eaf3f31`, where the `eaf3f31` is the most important part. Could you strip off everything before the final "/" or find some other way to shorten it?

**Comment by nawatts** [comment]
> Could you strip off everything before the final "/" or find some other way to shorten it?

Done in https://github.com/DataBiosphere/terra-ui/pull/4047/commits/8a49e31ce9223c906e7eca7710065dd7a7a6c279.

**Comment by nawatts** [comment]
Rebased to update test added in #4045.

**Review by davidangb — APPROVED** [review]
thank you!

**Review by calypsomatic — APPROVED** [review]
Thank you!

**Pull request merged**
