### PR TITLE
[IA-3436] Comment out analysis-context-bar and run-notebook tests

### PR DESCRIPTION
**Pull request by xuscrbw**
Commenting these two tests out until Leo release to production occurs. The error is due to an image in the dropdown not being cached yet.

<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

### CODE REVIEW

**Review by kyuksel — APPROVED** [review]
👍🏼 pending fixing the linting issues

**Comment by cahrens** [comment]
It looks like this is still failing. :( I guess I was wrong about the amount of changes that need to be done to disable a test.

FAIL  jest/1-analysis-context-bar.integration-test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../.yarn/__virtual__/@jest-core-virtual-0b58933bea/0/cache/@jest-core-npm-27.5.1-b2d79816b3-904a94ad8f.zip/node_modules/@jest/core/build/TestScheduler.js:175:18)
      at ../.yarn/cache/emittery-npm-0.8.1-9771f0f260-2457e8c7b0.zip/node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (../.yarn/cache/emittery-npm-0.8.1-9771f0f260-2457e8c7b0.zip/node_modules/emittery/index.js:258:23)

**Comment by cahrens** [comment]
@xuscrbw I pushed up a proposed deleting PR https://github.com/DataBiosphere/terra-ui/pull/3062

Since the commit can just be reverted to re-enable the test, I don't see any harm in simply deleting the jest files (and avoiding the whole "Your test suite must contain at least one test" issue).

**Comment by kyuksel** [comment]
Closing since another PR (#3062) was merged to accomplish what this PR was to

**Pull request closed without merging**
