### PR TITLE
DFE-816 Changes to BDC  terra branding

### PR DESCRIPTION
**Pull request by kilonzi**
Made changes to BDC Terra logos, favicon and primary accent color

Screenshot 2023-01-27 at 10 00 33

### CODE REVIEW

**Comment by cahrens** [comment]
@kilonzi did you optimize the SVGs (` yarn optimize-image-svg`)?

**Comment by kyuksel** [comment]
> @kilonzi did you optimize the SVGs (` yarn optimize-image-svg`)?

@kilonzi Let's make sure the `jpg` is optimized as well. [Some reference info](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide#images) in case it helps.

**Review by kyuksel — APPROVED** [review]
Looks good to me pending confirmation that the updated `svg` and `jpg` were optimized.

**Comment by kyuksel** [comment]
As an aside, it may be good to move the [this Confluence content](https://broadworkbench.atlassian.net/wiki/spaces/WOR/pages/2369388553/Cobranding+and+White+Label+Sites) to the [Contributor Guide wiki](https://github.com/DataBiosphere/terra-ui/wiki/Contributor-Guide) with its own section.

**Comment by kilonzi** [comment]
> 

@cahrens Thank you for the review. I have optimized them.

**Review by cahrens — APPROVED** [review]

**Pull request merged**
