### PR TITLE
[DC-487] Add catalog export case to import-data

### PR DESCRIPTION
**Pull request by s-rubenstein**
<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Also, so if a screen recording [1] and/or screenshots would be a helpful way to communicate context, please consider including some in your PR description.
Thanks!

[1] https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/mac
--!>

### CODE REVIEW

**Review by fboulnois — APPROVED** [review]
Well, that's convenient! Do we need unit test mocks for this functionality?

**Review by pshapiro4broad — APPROVED** [review]
Looks good. I assume export for snapshots will be a bit more messy...

**Comment by pshapiro4broad** [comment]
So the code that uses this new export case will be a separate PR? Is there a way to test this in the UI at this point? Or were we already calling this code with `catalog`?

**Review by breilly2 — APPROVED** [review]
👍 I'll confess that I didn't test this because I don't have enough familiarity with the Data Catalog domain, but the code looks fine to me.

**Comment by s-rubenstein** [comment]
@pshapiro4broad yeah, exporting snapshots will be much more tricky! This is not currently called with the catalog, although I could test this by hand-rolling a URL with the right query params. I may try to do that.

@fboulnois its unclear to me what we do for unit tests rn in the UI. I would say we may want to add a test similar to what we have for other tests for this, but we need to wait for that until the button works.

**Comment by s-rubenstein** [comment]
I have manually tested now with both existing and new workspace, and the new code works

**Pull request merged**
