### PR TITLE
AJ-873: Remove creation of Leo App in Terra UI

### PR DESCRIPTION
**Pull request by aaronkanzer**
Relates to https://broadworkbench.atlassian.net/browse/AJ-873

and changes in https://github.com/broadinstitute/rawls/pull/2283

### CODE REVIEW

**Review by aherbst-broad — APPROVED** [review]

**Review by yuliadub — APPROVED** [review]

**Review by calypsomatic — APPROVED** [review]

**Review by davidangb — COMMENTED** [review]
I much prefer #3877 to this one! We could merge this PR (or a similar one) to remove the call entirely a few weeks after #3877 goes out and we're happily creating WDSes in the back end.

**Review by davidangb — CHANGES_REQUESTED** [review]
marking as needing changes, in favor of #3877. We may want to just close this one.

**Comment by cahrens** [comment]
@davidangb can this be closed?

**Comment by davidangb** [comment]
closing as obsolete.

**Pull request closed without merging**
