### PR TITLE
IA-4003: delete disk always if azure runtime from CE page

### PR DESCRIPTION
**Pull request by lucymcnatt**
fixing issue with [earlier pr](https://github.com/DataBiosphere/terra-ui/pull/3751/files) not deleting the disk when deleting the runtime from the Cloud environments page

### CODE REVIEW

**Review by n8landolt — APPROVED** [review]
Ticket or subtask please!

**Comment by mlilynolting** [comment]
Was this not working previously because of asynchronicity with setDeleteDisk? Like it wasn't `true` yet when it got to the ajax call?

**Comment by lucymcnatt** [comment]
> Was this not working previously because of asynchronicity with setDeleteDisk? Like it wasn't `true` yet when it got to the ajax call?

I'm pretty sure this was the case yeah

**Review by ghost — APPROVED** [review]
I approve!

**Review by mlilynolting — APPROVED** [review]

**Pull request merged**
