### PR TITLE
[WM-2612] Adds support for submissions in Queued state in Azure

### PR DESCRIPTION
**Pull request by salonishah11**
### What
- Adds support for submissions & workflows being in Queued state
- Doesn't allow aborting submissions in Queued state

A Queued submission in Submission History page:
Screenshot 2024-05-17 at 4 48 38 PM

Can't Abort a submission in Queued state:
Screenshot 2024-05-17 at 4 48 47 PM

When workflows in a submission are in Queued state, it will show this message in the `Workflow Data`:
Screenshot 2024-05-17 at 1 47 10 PM

### Why
- With the introduction of async submissions in CBAS, when a submission is created they are in Queued state. See associated PR https://github.com/DataBiosphere/cbas/pull/281

### Testing strategy

- [x] Added unit test
- [x] Manually tested the changes

### CODE REVIEW

**Review by kpierre13 — APPROVED** [review]

**Review by aednichols — COMMENTED** [review]
I feel like "oops, I didn't mean to launch that" is a pretty common use case for Abort.

If a submission is queued in CBAS and hasn't made it to Cromwell yet, can we support Abort (or "Cancel" or whatever...) by simply removing it from the queue and never submitting it to Cromwell?

**Review by mspector — APPROVED** [review]

**Comment by mspector** [comment]
I like @aednichols 's idea, but in my opinion, it's a good candidate for the next slice of this feature

**Comment by cjllanwarne** [comment]
>If a submission is queued in CBAS and hasn't made it to Cromwell yet, can we support Abort (or "Cancel" or whatever...) by simply removing it from the queue and never submitting it to Cromwell?

I think that's the long term plan. This PR removes one source of inconsistency that actually already exists in the UI (seeing a submission's details before CBAS finishes processing it, currently in memory). In the longer run I imagine we want to do **_everything_** in a more controlled way that would enable better hooks like abort-before-submitting.

**Comment by salonishah11** [comment]
@aednichols yes that is definitely the long term plan. As Chris said the plan after this first iteration of async submissions is to do things asynchronously on a more controlled manner to support this abort use case.

**Review by aednichols — APPROVED** [review]
Sounds good to me!

**Pull request merged**
