### PR TITLE
[IA-3947] Add IA ownership

### PR DESCRIPTION
**Pull request by jdcanas**

### CODE REVIEW

**Comment by nawatts** [comment]
Suggest also adding relevant integration tests.

**Review by Qi77Qi — APPROVED** [review]
lgtm. Think Nick's comment makes sense too

**Review by nawatts — COMMENTED** [review]
@jack-r-warren renamed the team to `broad-interactive-analysis`, so the codeowners file will need to be updated accordingly.

See https://broadinstitute.slack.com/archives/C4P1S6KB8/p1673997608834829?thread_ts=1673990841.043659&cid=C4P1S6KB8.

**Comment by cahrens** [comment]
Please keep in mind that adding your team as required reviewers will mean that you will need the capacity to review PRs in a timely fashion. Recently I know your team has been swamped with other things, and it's been difficult for me to get IA reviews.

**Review by nawatts — APPROVED** [review]

**Review by n8landolt — APPROVED** [review]

**Pull request merged**
