### PR TITLE
WDL 1.0 tweaks [CA-335]

### PR DESCRIPTION
**Pull request by dmohs**
Changes come from looking at the latest commits in https://github.com/broadinstitute/wdl-sublime-syntax-highlighter.
Not sure how to test. Suggestions welcome.

### CODE REVIEW

**Review by panentheos — APPROVED** [review]
Looks good. I did a quick manual test and it works as expected. I think that this is a reasonable change since it mirrors the changes to the official highlighter.

**Comment by zarsky-broad** [comment]
Would this degrade highlighting for older versions, though? Perhaps the thing to do is to only add to the lists?

**Comment by dmohs** [comment]
@zarsky-broad That degrades the current version, since highlighting a now unreserved word may cause concern. I also removed `command` from the keywords list to be more in-line with the official highlighter even though I think it might be nice to highlight that word since it is a required literal for starting that block. Rest assured, this highlighter remains substantially more advanced than the official one because of its ability to highlight embedded languages :)

**Comment by dmohs** [comment]
@zarsky-broad Are you cool with my reasoning there?

**Comment by zarsky-broad** [comment]
I suppose. I think removing potentially helpful highlighting in favor of what's "correct" is icky, but I recognize that the alternative is to cause potential confusion. When will 1.0 support actually go in? I presume we would want to hold off on merging this until then, yes?

**Comment by dmohs** [comment]
@zarsky-broad Great call on getting Adam's input.

**Comment by zarsky-broad** [comment]
We are now more in line with the intellij plugin for behavior.

**Pull request merged**
