### PR TITLE
[DC-1204]Improve Spacing in Concept Search table

### PR DESCRIPTION
**Pull request by cinyecai**
### What
- Evened widths of all columns except Concept Name
- Increased line height so that multi-line concept names weren't as squished
- Increased spacing between Concept Name and Concept ID columns
- Truncated Concept Codes that overflowed when the window got too small

### Why
- Enhancing readability and aesthetic of Concept Search table

### Testing strategy

Tested by running UI locally and checking in with Lou and Victoria

https://github.com/user-attachments/assets/9cbd1821-721a-4c44-966f-c077f0d9d85f

### CODE REVIEW

**Review by rjohanek — COMMENTED** [review]
This looks good. Did we want a tooltip for truncated data like the code?

**Comment by cinyecai** [comment]
> Did we want a tooltip for truncated data like the code?

We considered this but came to find that it's difficult to get a tooltip that only shows up on truncated data (can only make it so that it always shows up regardless of truncation or not, which is kind of annoying), working with the Tooltip components we already have in Terra UI

**Review by rjohanek — APPROVED** [review]
Spacing changes look good and looks good without the tooltip

**Review by pshapiro4broad — APPROVED** [review]
Looks ok to me. It's probably out of scope for this ticket, but the concept hierarchy view also has a concept code and name field, which may also need truncating and/or multi-line formatting. Although that component uses `Grid` not `SimpleTable` so it likely has completely different display behavior. I wonder if there'd be a benefit in using `Grid` for both views?

**Comment by cinyecai** [comment]
> Looks ok to me. It's probably out of scope for this ticket, but the concept hierarchy view also has a concept code and name field, which may also need truncating and/or multi-line formatting. Although that component uses `Grid` not `SimpleTable` so it likely has completely different display behavior. I wonder if there'd be a benefit in using `Grid` for both views?

Thanks for the feedback! I looked into this a little and from what I've seen, the name already wraps to a new line if it's long, and the columns have enough space to support longer concept codes. I didn't look very thoroughly though (I looked at condition and devices hierarchies), so there could be other places where it's a bigger issue. The use of Grid instead of SimpleTable is interesting and may be worth looking into at some point, but I think if SimpleTable is working now for the Concept Search table, it might be more work than it's worth to change it to a Grid.

**Pull request merged**
