### PR TITLE
Adding a Duke researcher to whitelist

### PR DESCRIPTION
**Pull request by wnojopra**

### CODE REVIEW

**Comment by katevoss** [comment]
@wnojopra I tried to resolve the merge conflict but I got a little confused. In the end it looks like you only added one new entry to the Whitelist, is that correct?

**Comment by wnojopra** [comment]
@katevoss Yes that is correct, only one new entry. My commit history may be a bit confusing here, if it helps you, I'll clean this branch up in a few moments.

**Comment by wnojopra** [comment]
@katevoss Sorry for the confusion, I believe this should be easier to merge.

**Comment by katevoss** [comment]
@wnojopra Thanks for clarifying your commits. Now that it is merged, the researcher will have access to Terra tomorrow after 10am EST.

**Pull request merged**
