### PR TITLE
Upgrade follow-redirects to 1.14.9 [BW-1127]

### PR DESCRIPTION
**Pull request by aednichols**
<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Review by cjllanwarne — APPROVED** [review]

**Review by kyuksel — APPROVED** [review]
Haven't tested. It seems safe from 

```
$ yarn why -R follow-redirects
└─ terra-ui@workspace:.
   └─ react-scripts@npm:4.0.3 [3bc50] (via npm:4.0.3 [3bc50])
      └─ webpack-dev-server@npm:3.11.1 [b26ff] (via npm:3.11.1 [b26ff])
         └─ http-proxy-middleware@npm:0.19.1 (via npm:0.19.1)
            └─ http-proxy@npm:1.18.1 (via npm:^1.17.0)
               └─ follow-redirects@npm:1.14.7 [a313c] (via npm:^1.0.0 [a313c])
```

Could not find the changelog for some reason but it's a patch version change so…what could go wrong™

**Comment by aednichols** [comment]
Did some basic clicking around locally and all seems well.

**Comment by cahrens** [comment]
@aednichols there is still an alert for the integration test usage. Can you please clean that up also?

**Comment by aednichols** [comment]
https://github.com/DataBiosphere/terra-ui/pull/2867

**Pull request merged**
