### PR TITLE
block non-public pages until profile is loaded

### LINKED ISSUE #1237: Workspaces Added/Shared E-mail Notifications
User is getting email notifications whenever their account is added to or removed from a workspace share list but  all "account notifications" are un-checked in their profile. 
image

### PR DESCRIPTION
**Pull request by panentheos**
I _think_ this fixes #1237 

In trying to reproduce that, I found an issue where the page breaks if the profile hasn't finished loading by the time it mounts. This fixes that issue, which I suspect was responsible for the original bug report.

### CODE REVIEW

**Comment by elizzhao** [comment]
I'm a little confused on how this PR deals with the email notification problem outlined in #1237 
is this actually for #1344 ?

**Comment by panentheos** [comment]
@elizzhao I believe this is related to the linked issue (see the original PR comment)

**Comment by elizzhao** [comment]
Ah I get it--thanks for clarifying!

**Review by elizzhao — APPROVED** [review]
Changes make sense and looks like it would solve the specified problem. 

However, I wasn't able to reproduce the bug of the original ticket or the profile mounting problem mentioned in this PR, so my approval comes with that caveat!

**Pull request merged**
