### PR TITLE
ID-818, ID-819, ID-916 New Registration Flow, ToS Improvements (revert the revert with fixes)

### PR DESCRIPTION
**Pull request by tlangs**
(This is a re-implementation of https://github.com/DataBiosphere/terra-ui/pull/4482, which was reverted)

### Jira Ticket: https://broadworkbench.atlassian.net/browse/ID-916

This is the last step of https://broadworkbench.atlassian.net/browse/ID-787. So, it relies on basically all other tickets being done.

## Summary of changes:
- Users now accept the Terra Terms of Service during registration, instead of as a second step afterwards.
- Terra-UI now supports a Rolling Acceptance Window for Terms of Service update.
- Numerous improvements to user registration and login.

### What
- `Register.tsx` has been updated to prevent a new user from registering until the Terms of Service has been accepted. This is done by disabling the `Register` button until the user has loaded the Terms of Service and checked a checkbox that says the user accepts the Terms of Service. The checkbox is not active until the Terms of Service has been loaded, preventing users from checking the checkbox before they've actually seen the Terms of Service.
- Rendering of remote Markdown content has been encapsulated in `RemoteMarkdown.tsx` 
- `TermsOfServicePage.tsx` has been converted to tsx. The page has been significantly simplified and Grace Period functionality has been removed. If no action is needed, a `Return to Terra` button now appears. The page also uses `RemoteMarkdown` instead of handling the Terms of Service text downloading itself.
- `PrivacyPolicy.tsx` now uses `RemoteMarkdown` instead of handling the Privacy Policy text download itself.
- Old Terms of Service API calls have been removed and replaced with `Ajax().TermsOfService`, which call new Sam endpoints.
- `registrationStatus` has been removed and its functionality incorporated into `signInStatus`. There is now one place to check if the user has authenticated via B2C, registered for Terra, or signed out.
- Rolling Acceptance Window has been implemented as a replacement for Grace Period. The Rolling Acceptance Window allows the user to keep using Terra if the Terms of Service is updated during their active session, but forces them to accept the Terms of Service when they log in. This will ensure that all users are operating under the most recent Terms of Service after 24h of ToS release.

### Why
- Terms of Service must be accepted before we record any information about the user. GDPR compliance! 
- The old Terms of Service update mechanism was clunky, confusing to users, and kicked everyone out of Terra once the Terms of Service update was forced. The new Rolling Acceptance Window is a much better user experience!
- New Sam endpoints that provide for a better user experience are now available.

### Testing strategy
- [x] Unit Tests for new code and functionality.
- [x] `register-user` CUJ test has been updated to test new Terms of Service functionality.
- [x] Extensive manual testing in BEEs and Dev will be done to verify functionality.

 

https://github.com/DataBiosphere/terra-ui/assets/3210510/824b09fc-22c8-451f-9063-8c69b6d11ce7

image
image

### CODE REVIEW

**Comment by cahrens** [comment]
@tlangs can you keep this in draft until it is ready to review? It's been hard understanding what the state of the PRs are.

**Comment by tlangs** [comment]
Done!

**Comment by tlangs** [comment]
@cahrens Major apologies for the git branch thrashing. Turns out, git can be hard! We believe this contains all the changes we've made, and no reverts of changes other people made!

**Review by Ghost-in-a-Jar — APPROVED** [review]

**Review by cahrens — APPROVED** [review]

**Comment by cahrens** [comment]
A note for reviewers: a squash of the post-revert commits can be seen [here](https://github.com/DataBiosphere/terra-ui/pull/4513/commits/221ae1d18cc7b21929e0d8ffc12f464839537a08).

**Pull request merged**
