### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by zarsky-broad**

### CODE REVIEW

**Review by elizzhao — COMMENTED** [review]
Thanks for doing this Isaac! Couple questions: 
Does this also include the requirement that one of the code owners has to approve before merging? 
When/where do we add ourselves as code owners? Would it be after this gets merged?

**Comment by zarsky-broad** [comment]
1. Nope
2. I created the team that this refers to and added all of us last night

**Comment by elizzhao** [comment]
Got it, thanks--do we want to/can we include that stipulation?

**Comment by zarsky-broad** [comment]
I think that's a repo setting, not something in the doc

**Review by katevoss — APPROVED** [review]
Requiring a review from a Code Owner is a repo setting: https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests 
I believe @panentheos is our repo admin who can make this change, if we decide to do it. For now we can just try out the code owner process and see if we like it.

**Review by elizzhao — APPROVED** [review]
Previous questions got answered!

**Comment by zarsky-broad** [comment]
Yup, and I'm an admin too.

**Pull request merged**
