### PR TITLE
Update ua parser js

### PR DESCRIPTION
**Pull request by THWiseman**
Updated the `ua-parser-js` library, which was flagged as a security issue in [WX-942](https://broadworkbench.atlassian.net/browse/TUIM-54?atlOrigin=eyJpIjoiZDIwMmQyNDI5NThmNDQyYWEwODMwM2EyZGJiMDYwOGQiLCJwIjoiaiJ9). 

While we don't depend on `ua-parser-js` directly, two packages `react-json-view` and `outdated-browser-rework` were using it. I tested that these still work by interacting with these components/pages on my local front end. I can indeed still view JSON, and I am redirected when using an oudated browser. 

[WX-942]: https://broadworkbench.atlassian.net/browse/WX-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nawatts — CHANGES_REQUESTED** [review]
This does not upgrade existing instances of this package. It adds a new (unused) instance of the package. You can tell because the old version still shows up in yarn.lock.

See https://github.com/DataBiosphere/terra-ui/wiki/Security-and-Maintenance#dependabot-security-updates for instructions on how to update transitive dependencies.

**Comment by THWiseman** [comment]
> This does not upgrade existing instances of this package. It adds a new (unused) instance of the package. You can tell because the old version still shows up in yarn.lock.
> 
> See https://github.com/DataBiosphere/terra-ui/wiki/Security-and-Maintenance#dependabot-security-updates for instructions on how to update transitive dependencies.

My mistake. Will look into it this afternoon and fix.

**Comment by THWiseman** [comment]
Fixes made, followed the documentation this time around 😅 . Repeated the testing and was still able to interact successfully with relevant components.

**Review by nawatts — CHANGES_REQUESTED** [review]
Now this updates many more libraries than it needs to, not only ua-parser-js.

Starting from the dev branch, removing the following section from yarn.lock (to unlock the version of ua-parser-js) and then running yarn should update only ua-parser-js.
```
"ua-parser-js@npm:^0.7.22, ua-parser-js@npm:^0.7.30":
  version: 0.7.31
  resolution: "ua-parser-js@npm:0.7.31"
  checksum: e2f8324a83d1715601576af85b2b6c03890699aaa7272950fc77ea925c70c5e4f75060ae147dc92124e49f7f0e3d6dd2b0a91e7f40d267e92df8894be967ba8b
  languageName: node
  linkType: hard
```

**Comment by nawatts** [comment]
Ah, I see. The extra updates are from `yarn dedupe`.

Not sure I agree that a `yarn dedupe` step should be included in Dependabot updates, but it should be fine and can't fault this change for following the documented process.

**Review by nawatts — APPROVED** [review]

**Review by aednichols — APPROVED** [review]

**Pull request merged**
