### PR TITLE
[CA-1501] Sr merge dev into v2_workspaces

### PR DESCRIPTION
**Pull request by s-rubenstein**
<!--
Hello, friend!
Remember to mention what sort of testing/verification you performed in the course of building this PR, i.e. checking functionality in the browser locally.
Thanks!
--!>

### CODE REVIEW

**Comment by andy7i** [comment]
anything you want to flag for us to review? Since this is merging dev into our feature branch, I'm inclined to say most of it does not need review since it has already been reviewed before it was merged into dev.

**Comment by s-rubenstein** [comment]
I don't think there's anything in particular. I am going to do a quick smoke test of standing it up locally.

**Review by andy7i — APPROVED** [review]
haven't reviewed the code 👍 
(merging latest into feature branch with nothing in particular to review)

**Review by marctalbott — APPROVED** [review]
Same as Andrew, thumbed based on the fact that this was all approved before going to dev

**Pull request merged**
