### PR TITLE
[TUIM-57] add webpack as direct dependency in order to upgrade version

### PR DESCRIPTION
**Pull request by blakery**
### What
* Add webpack as a direct dependency
* Update webpack version
### Why
a security vulnerability exists in previously used version of webpack
Adding webpack as a direct dependency was required because:
* create-react-app (aka react-scripts) is deprecated, and infrequently maintained, so we couldn't pick up the update downstream (ticket: [TUIM-58](https://broadworkbench.atlassian.net/browse/TUIM-58))
* neither of the two approaches documented in yarn worked
  - the `"resolutions"` field in `package.json` is removed by yarn on run of `yarn install` (it appears this feature was for earlier versions of yarn)
  -  running: `yarn set resolution -s webpack@npm:^5.5.0 ^5.81.0` didn't change anything (this appears to be the indicated approach for current verions of yarn)

### Testing strategy
* `yarn info webpack version` to check installed version of webpack (after `yarn install`)
* app still runs with `yarn start`
* tests still pass with `yarn test`

[TUIM-57]: https://broadworkbench.atlassian.net/browse/TUIM-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TUIM-58]: https://broadworkbench.atlassian.net/browse/TUIM-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nawatts** [comment]
Transitive dependencies do not need to be added as a direct dependencies in order to upgrade them. They can be upgraded by removing the yarn.lock entry for the old version.

https://github.com/DataBiosphere/terra-ui/wiki/Security-and-Maintenance#dependabot-security-updates

**Comment by cahrens** [comment]
@nawatts did you try it in this case? I tried deleting "react-scripts@npm:5.0.0" and "@svgr/webpack@npm:^5.5.0", but when I ran `yarn install` I ended up with the 5.5.0 version of webpack again. And then for snicks I deleted everything in yarn.lock and tried running `yarn install` and again ended up with the same version.

**Comment by nawatts** [comment]
Admittedly, I did not try it before making that comment.

But after deleting webpack's entry from yarn.lock:
```
"webpack@npm:*, webpack@npm:^5.64.4":
  version: 5.70.0
  resolution: "webpack@npm:5.70.0"
  ...
```

And running `yarn`, I end up with webpack upgraded from 5.70.0 to 5.81.0.

**Comment by cahrens** [comment]
Ah, so `svgr/webpack@npm` was the wrong thing to be deleting… thanks!

**Comment by blakery** [comment]
that worked - I'll close this and create a separate PR

**Pull request closed without merging**
