### PR TITLE
Add jest-html-reporter to Terra UI unit test config

### PR DESCRIPTION
**Pull request by mlilynolting**
## [jest-html-reporter](https://github.com/Hargne/jest-html-reporter) creates an HTML summary of unit test runs.
The default Jest reporter's command-line output overflows my terminal buffer if any tests produce stacktraces, making it impossible to see which tests failed without running test suites individually. This reporter adds a nice HTML summary!

Automatically generates a page and prints the link at the end of the test results. Test command is unchanged:
```
  > yarn test
```

Screenshot 2023-08-23 at 10 06 47 AM
Screenshot 2023-08-23 at 10 06 41 AM

## Dependencies
I'm *not* certain that the dependency upgrades included in this PR are correct - here's what I did:
* cleared the cache with `yarn clean`
* added the new package with `yarn add jest-html-reporter`
* ran `yarn install` to set up all my packages
* ran `yarn build-packages`

When I committed all this, CircleCI failed with some cached-package misses. I concluded that I needed to check in the cached package files which had changed:
* ran `git add ../.yarn/cache/*` and then committed again

### CODE REVIEW

**Review by nawatts — CHANGES_REQUESTED** [review]
Requesting changes over one thing: let's add the generated test-report.html to .gitignore.

Besides that (and I won't request changes over it), personally I'm skeptical of how generally useful this is. It seems like you can't see the output of failed tests in the HTML view. I guess I could see it being useful if there's a large number of test suites failing and you want to identify them: you can use the browser find to look for "failed" (though there are some test names that include that word). But for a single test failure, I found that information much more readily available from the default reporter.

**Comment by mlilynolting** [comment]
@nawatts I added the report file to .gitignore, and also added the configuration options which will display verbose test failures in the report. lmk if this puts it over the line for you!

Screenshot 2023-08-23 at 10 48 45 AM

(nb: For me, just having a reviewable list of all tests executed with their results is enough utility to make this worthwhile, since there's no way to do that on a complete run currently)

**Review by nawatts — APPROVED** [review]
Nice. With those latest changes, it's much easier for me to find the failed tests in the HTML view. I think adding the sort by status was a big improvement.

It would be nice if the HTML reporter collapsed the failed test output by default, but I don't see a configuration option for that.

**Comment by mlilynolting** [comment]
> It would be nice if the HTML reporter collapsed the failed test output by default, but I don't see a configuration option for that.

There is an option to collapse everything, but then you don't have any visual indication that the suite failed without expanding it. I also inspected the HTML output and it doesn't look like suite elements with only failures/only successes are assigned any special class, so a beautification would have to involve custom JS.

**Review by cahrens — APPROVED** [review]

**Pull request merged**
